// Akwa Ibom facilities, sourced from EnVo's facility register (state = 'Akwa Ibom').
// Embedded rather than read from EnVo's database so this project stays self-contained;
// re-run is safe (envo_facility_id is unique, conflicts are skipped).
// [name, lga, envo_facility_id]
export const AKWA_IBOM_FACILITIES = [
  ["Afaha Obong Primary Health Centre","Abak","AOP005"],
  ["Ebom Primary Health Centre","Abak","EPH044"],
  ["Mercy Hospital","Abak","MH172"],
  ["Uduak Abasi Clinic","Abak","UAC253"],
  ["Ukpom Abak General Hospital","Abak","UAG259"],
  ["Iko Town Primary Health Centre","Eastern Obolo","ITP106"],
  ["Effoi Primary Health Centre","Eket","EPH047"],
  ["Eket Immanuel General Hospital","Eket","EIG051"],
  ["Ikot Ebok Primary Health Centre (Operational Base)","Eket","IEP116"],
  ["Okon Eket Comprehensive Health Centre","Eket","OEC220"],
  ["Ekpene Obo Cottage Hospital","Esit Eket","EOC055"],
  ["Idung Assan Health Centre","Esit Eket","IAH099"],
  ["Uquo Primary Health Centre","Esit Eket","UPH266"],
  ["Adiasim Health Centre","Essien Udim","AHC002"],
  ["Afaha Ikot Ebak Primary Health Centre","Essien Udim","AIE004"],
  ["Ekpenyong 1 Midim Atan Health Centre","Essien Udim","EM057"],
  ["Ikot Akpan Effia Health Centre","Essien Udim","IAE112"],
  ["Ikot Ide Health Centre","Essien Udim","IIH129"],
  ["Ikpe Annang General Hospital","Essien Udim","IAG140"],
  ["Ikpe Annang Health Centre","Essien Udim","IAH141"],
  ["St. Mary's Hospital, Uruakpan","Essien Udim","SMH247"],
  ["Ukana Cottage Hospital","Essien Udim","UCH255"],
  ["Ukana East Primary Health Centre","Essien Udim","UEP256"],
  ["Ukana Iba St Joseph's rehabilitation Centre","Essien Udim","UIS257"],
  ["Etim Ekpo General Hospital","Etim Ekpo","EEG065"],
  ["Etim Ekpo Primary Health Centre","Etim Ekpo","EEP066"],
  ["Ikot Ebo Health Centre","Etim Ekpo","IEH117"],
  ["Utu Etim Ekpo Divine Love Hospital","Etim Ekpo","UEE271"],
  ["Ekpene Obom QIC Rehabilitation Hosp","Etinan","EOQ056"],
  ["Etinan General Hospital","Etinan","EGH067"],
  ["Etinan Primary Health Centre","Etinan","EPH068"],
  ["Ikot Obio Inyang Primary Health Centre","Etinan","IOI132"],
  ["Ndon Utim Primary Health Centre","Etinan","NUP180"],
  ["Ibeno Cottage Hospital","Ibeno","ICH090"],
  ["Iwuo Achang Health Post","Ibeno","IAH149"],
  ["Mkpanak Primary Health Center","Ibeno","MPH174"],
  ["Akpautong Mt. Camel Hospital","Ibesikpo Asutan","AMC014"],
  ["Ikot Iko Primary Health Centre","Ibesikpo Asutan","IIH130"],
  ["Ikot Obio Edim Health Centre","Ibesikpo Asutan","IOE131"],
  ["Nung Udoe Model Primary Health Centre","Ibesikpo Asutan","NUM190"],
  ["Nung Udoe Primary Health Centre","Ibesikpo Asutan","NUP191"],
  ["Ibiono Handmaids Hospital","Ibiono-Ibom","IHH094"],
  ["Ibiono Palmer Memorial Hospital","Ibiono-Ibom","IPM095"],
  ["Ikot Adaidem Primary Health Centre","Ibiono-Ibom","IAP110"],
  ["Ikot Idaha Primary Health Centre","Ibiono-Ibom","IIP128"],
  ["Ikpa Ikot Uneke Primary Health Centre","Ibiono-Ibom","IIU139"],
  ["Nsan Health Centre","Ibiono-Ibom","NHC182"],
  ["Ntan Ibiono Eduwem Clinic","Ibiono-Ibom","NIE186"],
  ["Use Abat St. Theresa's Hospital","Ibiono-Ibom","UAS268"],
  ["Nto Etuk Udo Health Centre","Ika","NEU189"],
  ["Urua Inyang Primary Health Centre","Ika","UIP267"],
  ["Ediene I Health Centre","Ikono","EIH046"],
  ["Etip Ediene Primary Health Centre","Ikono","EEP069"],
  ["Ibiaku Primary Health Centre (BASE)","Ikono","IPH092"],
  ["Ikono General Hospital","Ikono","IGH107"],
  ["Nung Ukim Health Centre","Ikono","NUH192"],
  ["Ukpom-Ikono Primary Health Centre","Ikono","UPH260"],
  ["Base Ikot Abasi Primary Health Centre","Ikot Abasi","BIA027"],
  ["Ikot Abasi General Hospital","Ikot Abasi","IAG108"],
  ["Abiakpo Ikot Essien Health Centre","Ikot Ekpene","AIE001"],
  ["Confidence Maternity/Health care Services","Ikot Ekpene","CMS033"],
  ["Demak Clinic","Ikot Ekpene","DC040"],
  ["Ememobong Maternity","Ikot Ekpene","EM060"],
  ["Evergreen Medical Centre","Ikot Ekpene","EMC070"],
  ["Ikot Ekpene General Hospital","Ikot Ekpene","IEG122"],
  ["Ikot Ekpene Infectious Disease Hospital","Ikot Ekpene","IEI123"],
  ["Ikot Ekpene Primary Health Centre","Ikot Ekpene","IEP124"],
  ["Ikot Out Health Centre","Ikot Ekpene","IOH136"],
  ["Ikot Udoe Health Centre","Ikot Ekpene","IUH137"],
  ["Ikpe Ikot Nkon General Hospital","Ini","IIN142"],
  ["Iwerre Health Centre","Ini","IHC148"],
  ["Mbia Obong Ikot Udofia Primary Health Centre","Ini","MOI164"],
  ["Odoro Ikpe Operational Base","Ini","OIO202"],
  ["Usuk Ibakasi Primary Health Centre","Ini","UIP270"],
  ["Ibom Specialist Hospital","Itu",null],
  ["Ikot Andem Itam Primary Health Centre","Itu","IAI114"],
  ["Mary Slessor General Hospital","Itu","MSG159"],
  ["Mbak Atai Operational Base Primary Health Centre","Itu","MAO162"],
  ["Mbiabong Itam Health Centre","Itu","MIH165"],
  ["Ntak Inyang Model Primary Health Centre","Itu","NIM185"],
  ["West Itam Primary Health Centre","Itu","WIP278"],
  ["Ebughu Primary Health Center","Mbo","EPH045"],
  ["Enwang Primary Health Centre","Mbo","EPH062"],
  ["Ibaka Primary Health Centre","Mbo","IPH089"],
  ["Uda Health Centre","Mbo","UHC252"],
  ["Uyenghe Primary Health Centre","Mbo","UPH273"],
  ["Ikot Abia Cottage Hospital","Mkpat-Enin","IAC109"],
  ["Mkpat Enin Primary Health Centre","Mkpat-Enin","MEP175"],
  ["Ikot Edebe Health Centre","Nsit-Atai","IEH118"],
  ["Nsit Atai Primary Health Centre","Nsit-Atai","NAP183"],
  ["Afaha Offiong Primary Health Care Operational Base","Nsit-Ibom","AEO003"],
  ["Mbiokporo I Model Primary Health Centre","Nsit-Ibom","MIM168"],
  ["Akai Ubium Cottage Hospital","Nsit-Ubium","AUC009"],
  ["Ikot Ekpene Udo Cottage Hospital","Nsit-Ubium","IEU125"],
  ["Ikot Ekwere Model Primary Health Centre","Nsit-Ubium","IEM127"],
  ["Nsit Ubium Primary Health Centre","Nsit-Ubium","NUP184"],
  ["Ikot Utu Model Primary Health Centre","Obot Akara","IUM138"],
  ["Nto Edino Comprehensive Health Centre","Obot Akara","NEC187"],
  ["Nto Edino Primary Health Centre","Obot Akara","NEP188"],
  ["Obot Akara Primary Health Centre","Obot Akara","OAP197"],
  ["Eweme Model Primary Health Centre","Okobo","EMP071"],
  ["Ima Abasi Maternity Home, Ekeya","Okobo","IAM145"],
  ["Mbokpu Oduobo Primary Health Centre","Okobo","MOP169"],
  ["Okobo General Hospital","Okobo","OGH209"],
  ["Okopedi Primary Health Centre","Okobo","OPH210"],
  ["Oti Oro Primary Health Centre","Okobo","OOP225"],
  ["Base Abat Primary Health Centre","Onna",null],
  ["General Hospital Awa","Onna","OCH216"],
  ["Ikot Eko Ibon Cottage Hospital","Onna","IEI121"],
  ["Esin Ufot Primary Health Centre","Oron","EUP063"],
  ["Eyo Abasi Health Post","Oron","EAH072"],
  ["Idua Assang Health Post","Oron","IAH098"],
  ["Oron Christ Victory Medical Centre","Oron","OCV219"],
  ["Oron General Hospital (Iquita)","Oron","OGH221"],
  ["Oron Operational Base Primary Health Centre","Oron","OBP217"],
  ["Priscon Clinic","Oron","PC233"],
  ["St Patricks Clinic","Oron","SPC244"],
  ["Uwem Foundation Specialist Hospital","Oron","UFS272"],
  ["Ekparakwa Health Centre","Oruk Anam","EHC053"],
  ["Ikot Akpan Essien Health Centre","Oruk Anam","IAE113"],
  ["Ikot Ibritam Primary Health Centre Operational Base","Oruk Anam","OAP222"],
  ["Ikot Okoro General Hospital","Oruk Anam","IOG133"],
  ["Eyo Okponung Primary Health Centre","Udung-Uko","EOP073"],
  ["Eyofin Primary Health Centre","Udung-Uko","EPH074"],
  ["Ikot Akpa Nkuk Primary Health Centre","Ukanafun","IAN111"],
  ["Ekpene Ibia Primary Health Center","Uruan","EIP054"],
  ["Ibiaku-Uruan Primary Health Centre","Uruan","IPH093"],
  ["Ibiaku Isshiet Primary Health Centre","Uruan","IIP091"],
  ["Idu-Uruan Primary Health Centre","Uruan","IPH097"],
  ["Ikot Otoenyie Health Post","Uruan","IOH135"],
  ["Ituk Mbang Methodist General Hospital","Uruan","IMM147"],
  ["Mbiaya Comprehensive Health Centre","Uruan","MCH167"],
  ["Ndon Ebom Primary Health Center","Uruan","NEP179"],
  ["Nwaniba Primary Health Centre","Uruan","NPH193"],
  ["Use Primary Health Centre","Uruan","UPH269"],
  ["Base Urue Offong Primary Health Centre","Urue-Offong/Oruko","BUO028"],
  ["Ikpe Oro Health Post","Urue-Offong/Oruko","IOH143"],
  ["Mbokpu-Eyoakan Health Centre","Urue-Offong/Oruko","MHC170"],
  ["Oduonim Health Post","Urue-Offong/Oruko","OHP204"],
  ["Oruko General Hospital","Urue-Offong/Oruko","OGH223"],
  ["Oruko Primary Health Centre","Urue-Offong/Oruko","OPH224"],
  ["Oyoku Ibighi Health Centre","Urue-Offong/Oruko","OIH228"],
  ["First Line Clinics and Surgery","Uyo","FLC077"],
  ["Gateway Hospital","Uyo","GH078"],
  ["Idoro Obio Health Centre","Uyo","IOH096"],
  ["Ifa Atai Health Post","Uyo","IAH100"],
  ["Ikot Ayan Ikono Primary Health Centre","Uyo","IAI115"],
  ["Ikot Okubo Primary Health Centre","Uyo","IOP134"],
  ["LifeCare Clinic","Uyo","LC157"],
  ["Mbak Etoi Primary Health Centre","Uyo","MEP163"],
  ["Mbiabong Primary Health Centre","Uyo","MPH166"],
  ["Oku Model Health Centre Uyo","Uyo","OMH212"],
  ["Our Lady of Lourdes Infirmary","Uyo","OLO226"],
  ["Premier Medical Centre","Uyo","PMC232"],
  ["Sheltered Specialist Hospital","Uyo","SSH241"],
  ["St. Luke's Hospital Anua","Uyo","SLH246"],
  ["Ubong Abasi Specialist Clinic","Uyo","UAS251"],
  ["University of Uyo Medical Centre","Uyo","UOU264"],
  ["University Teaching Hospital","Uyo","UTH265"],
  ["Uyo Base Primary Health Centre","Uyo","UBP274"],
  ["Uyo Police Hospital","Uyo","UPH275"],
  ["Uyo St Athanasius Medical Centre","Uyo","USA276"]
];
