// National LMIS print forms — exact-match reproductions of the government tools
// (Bin Card, Internal RIRV, Transfer & Return, CRRF variants) with the Nigerian
// coat of arms. Opened via the app's Print / Save as PDF buttons. This module is
// dynamically imported so the ~420KB coat-of-arms SVG stays out of the main bundle.
import ncoa from '../assets/ncoa.svg?raw'
import { toast } from '../components/ui/Toast'
import { fmtDate } from './helpers'

const esc = s => String(s == null ? '' : s).replace(/[&<>]/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;' }[c]))
const dstr = d => (d ? fmtDate(d) : '')
// Movement cells: show the number, blank when zero/empty (paper-form convention).
const q = n => (n === 0 || n == null || n === '') ? '' : Number(n).toLocaleString()
const signed = n => n > 0 ? `+${Number(n).toLocaleString()}` : n < 0 ? Number(n).toLocaleString() : ''
const line = (v = '', w = 90) => `<span class="fill" style="min-width:${w}px">${esc(v)}</span>`

// Shared print stylesheet — ported verbatim from the approved preview.
const CSS = `
  *{ box-sizing:border-box; font-family:Arial,Helvetica,sans-serif; -webkit-print-color-adjust:exact; print-color-adjust:exact; }
  body{ margin:0; color:#111; }
  .paper{ padding:10mm 10mm 12mm; }
  .hdr{ display:flex; align-items:center; gap:18px; border-bottom:2px solid #000; padding-bottom:8px; }
  .arms{ width:78px; height:66px; flex:none; display:flex; align-items:center; justify-content:center; }
  .arms svg{ height:64px; width:auto; }
  .ttl{ flex:1; text-align:center; }
  .ftitle{ font-size:16px; font-weight:800; letter-spacing:1px; }
  .fsub-band{ border:1px solid #000; border-top:none; text-align:center; font-weight:700; font-size:12px; padding:3px 4px; }
  .fsub-band u{ font-weight:700; }
  .fields{ margin:12px 0 8px; font-size:11.5px; line-height:2.0; }
  .frow{ display:flex; gap:24px; } .f{ flex:1; }
  .hint{ color:#666; font-size:9.5px; }
  .fill{ display:inline-block; border-bottom:1px solid #000; padding:0 4px; min-height:15px; }
  table{ width:100%; border-collapse:collapse; font-size:10.5px; margin-top:4px; }
  th,td{ border:1px solid #000; padding:4px 6px; text-align:center; }
  th{ background:#e9e9e9; font-size:9.5px; line-height:1.15; font-weight:700; }
  td.l{ text-align:left; } td.n{ text-align:right; font-variant-numeric:tabular-nums; } td.b{ font-weight:700; }
  tbody tr{ height:25px; }
  tr.close td{ background:#e9eef5; font-weight:700; }
  .red{ color:#c0121a; font-weight:700; }
  .foot{ font-size:9px; color:#555; margin-top:8px; text-align:right; }
  .sigs{ display:grid; grid-template-columns:1fr 1fr; gap:6px 24px; margin-top:14px; font-size:10.5px; }
  .sigs.two{ grid-template-columns:1fr 1fr 1fr; }
  .sg{ padding:3px 0; } .lbl{ color:#333; }
  .cert{ margin-top:12px; font-size:10.5px; border-top:1px solid #999; padding-top:8px; line-height:1.9; }
  .cert .cm{ margin-top:4px; }
  .note{ margin-top:12px; font-size:11px; font-weight:700; text-align:center; letter-spacing:1px; }
  .fields.three .frow{ gap:20px; }
  tr.grp td{ background:#f2f2f2; font-weight:700; text-align:left; }
  .crrf th.rep{ background:#dfe7df; } .crrf th.req{ background:#e7dfdf; }
  .crrf tr.keys th{ background:#f5f5f5; font-style:italic; font-weight:400; color:#555; }
  .crrf.sm{ font-size:9px; } .crrf.sm th{ font-size:8px; } .crrf.sm td,.crrf.sm th{ padding:3px 4px; }
  .sub-h{ margin-top:14px; font-size:11.5px; font-weight:700; border-bottom:1px solid #999; padding-bottom:2px; }
  .mini{ font-size:10px; margin-top:4px; } .mini th{ font-size:9px; }
  .ver{ margin-top:8px; font-size:9px; color:#666; text-align:right; }
  @page{ size:landscape; margin:8mm; }
`

function armsHeader(title, sub = '') {
  const band = sub ? `<div class="fsub-band">${sub}</div>` : ''
  return `<div class="hdr"><div class="ttl"><div class="ftitle">${esc(title)}</div></div>`
    + `<div class="arms">${ncoa}</div></div>${band}`
}

// Open a print window with the given inner HTML, trigger the print dialog.
function openPrint(title, inner) {
  const doc = `<!DOCTYPE html><html><head><meta charset="utf-8"><title>${esc(title)}</title>`
    + `<style>${CSS}</style></head><body><div class="paper">${inner}</div>`
    + `<div class="foot">Generated by EnVo LMIS · ${esc(new Date().toLocaleString('en-GB'))}</div></body></html>`
  const url = URL.createObjectURL(new Blob([doc], { type: 'text/html' }))
  const win = window.open(url, '_blank')
  if (win) {
    win.onload = () => { win.focus(); win.print(); URL.revokeObjectURL(url); win.onafterprint = () => win.close() }
  } else {
    URL.revokeObjectURL(url)
    toast('Allow pop-ups to print / export PDF', 'red')
  }
}

// ── BIN CARD ──────────────────────────────────────────────────────────────
// Which of MAIN STORE / SUB STORE / DISPENSARY this bin is, for the subtitle.
function binKindLabel(location) {
  if (location === 'store') return 'MAIN STORE'
  if (location === 'dispensary') return 'DISPENSARY'
  return 'SUB STORE'   // DSD / SDP sites
}
const isGhsc = p => /ghsc/i.test(p || '')

export function printBinCard(card, locationLabel) {
  const comm = card?.commodity || {}
  const active = binKindLabel(card?.location)
  const sub = ['MAIN STORE', 'SUB STORE', 'DISPENSARY']
    .map(k => k === active ? `<u>${k}</u>` : k).join(' / ')

  // Opening balance, then movement rows with a monthly close-out band each month.
  const rows = card?.rows || []
  const bodyRows = []
  bodyRows.push(`<tr><td></td><td></td><td class="l">Balance b/f</td><td></td><td></td>`
    + `<td></td><td></td><td></td><td class="n b">${q(card?.openingBalance) || 0}</td><td></td><td></td></tr>`)

  const monthKey = d => { const x = new Date(d); return isNaN(x) ? '' : `${x.getFullYear()}-${x.getMonth()}` }
  const monthName = d => new Date(d).toLocaleString('en-GB', { month: 'long', year: 'numeric', timeZone: 'Africa/Lagos' }).toUpperCase()
  let curKey = null, mRecv = 0, mIss = 0, mAdj = 0, mBal = null, mDate = null
  const flush = () => {
    if (curKey == null) return
    bodyRows.push(`<tr class="close"><td colspan="2">${esc(monthName(mDate))} CLOSE-OUT</td>`
      + `<td>Monthly summary</td><td></td><td></td>`
      + `<td class="n">${q(mRecv)}</td><td class="n">${q(mIss)}</td><td class="n">${signed(mAdj)}</td>`
      + `<td class="n b">${q(mBal)}</td><td></td><td></td></tr>`)
  }
  for (const r of rows) {
    const k = monthKey(r.date)
    if (k !== curKey) { flush(); curKey = k; mRecv = 0; mIss = 0; mAdj = 0; mDate = r.date }
    mRecv += r.received || 0; mIss += r.issued || 0; mAdj += r.adjustment || 0; mBal = r.balance; mDate = r.date
    const party = String(r.party || '').replace(/^→\s*/, '')   // no arrows on the form
    const partyCell = isGhsc(party) ? `<td class="l red">${esc(party)}</td>` : `<td class="l">${esc(party)}</td>`
    bodyRows.push('<tr>' + `<td>${dstr(r.date)}</td><td>${esc(r.ref)}</td>` + partyCell
      + `<td>${esc(r.batch)}</td><td>${dstr(r.expiry)}</td>`
      + `<td class="n">${q(r.received)}</td><td class="n">${q(r.issued)}</td><td class="n">${signed(r.adjustment)}</td>`
      + `<td class="n b">${q(r.balance)}</td><td>${esc(r.by)}</td><td class="l">${esc(r.remarks)}</td></tr>`)
  }
  flush()

  const inner = armsHeader('BIN CARD', `( ${sub} )`) + `
    <div class="fields">
      <div class="frow"><div class="f">Name of Facility: ${line(card?.facility?.name, 340)}</div></div>
      <div class="frow"><div class="f">Item Description: ${line(comm.name, 240)} <span class="hint">(Name, Strength, Dosage Form)</span></div>
        <div class="f">Product Code: ${line()}</div><div class="f">Card No: ${line()}</div></div>
      <div class="frow"><div class="f">Unit of Measure: ${line(comm.unit)}</div><div class="f">Location / Shelf No: ${line()}</div></div>
    </div>
    <table><thead>
      <tr><th rowspan="2">Date</th><th rowspan="2">Voucher / Ref. No</th><th rowspan="2" style="width:16%">Received From / Issued to</th>
        <th rowspan="2">Batch No.</th><th rowspan="2">Expiry Date</th><th colspan="3">Quantity</th>
        <th rowspan="2">Balance</th><th rowspan="2">Signature</th><th rowspan="2">Remarks</th></tr>
      <tr><th>Received</th><th>Issued</th><th>Losses &amp; Adj.</th></tr></thead>
      <tbody>${bodyRows.join('')}</tbody></table>`
  openPrint(`Bin Card — ${comm.name || ''}`, inner)
}

// ── INTERNAL RIRV ─────────────────────────────────────────────────────────
const rx = (notes, tag) => new RegExp(`\\[${tag}:\\s*([^\\]]+)\\]`, 'i').exec(notes || '')?.[1]?.trim()
// Destination label from a redistribution's notes: DSD/SDP site, else Dispensary.
function moveDest(notes) {
  const dsd = rx(notes, 'DSD'); if (dsd) return `DSD — ${dsd}`
  const sdp = rx(notes, 'SDP'); if (sdp) return `SDP — ${sdp}`
  return 'Dispensary'
}
const sigRow = (role, val = '') => `<div class="sg"><span class="lbl">${role}</span> ${line(val, 150)} `
  + `<span class="lbl">Signature</span> ${line('', 90)} <span class="lbl">Date</span> ${line('', 80)}</div>`

// moveRows: the stock_transfer_log rows of ONE redistribution move (same
// destination). ctx: { facilityName, packSize(commodityId)->str, batches(id)->{batch,expiry} }.
export function printRIRV(moveRows, ctx = {}) {
  const rows = moveRows || []
  const first = rows[0] || {}
  const to = moveDest(first.notes)
  const pack = ctx.packSize || (() => '')
  const batches = ctx.batches || {}
  const bal = n => { const m = /balance:(\-?\d+)/.exec(n || ''); return m ? m[1] : '' }

  const lineRows = rows.map((r, i) => {
    const b = batches[r.id] || {}
    return '<tr>' + `<td>${i + 1}</td>` + `<td class="l">${esc(r.commodity_name)}</td>`
      + `<td>${esc(pack(r.commodity_id))}</td>` + `<td class="n">${q(bal(r.notes))}</td>`
      + `<td class="n">${q(r.qty_requested)}</td>` + `<td class="n">${q(r.quantity)}</td>`
      + `<td>${esc(b.batch || '')}</td>` + `<td>${dstr(b.expiry) || ''}</td>` + `<td class="l"></td></tr>`
  }).join('')
  // pad to a minimum of rows so the voucher keeps its shape
  const pad = Math.max(0, Math.min(15, 8 - rows.length))
  const blanks = Array.from({ length: pad }, (_, i) => `<tr><td>${rows.length + i + 1}</td>${'<td></td>'.repeat(8)}</tr>`).join('')

  const inner = armsHeader('INTERNAL REQUISITION, ISSUE &amp; RECEIPT VOUCHER') + `
    <div class="fields">
      <div class="frow"><div class="f">Name of Facility: ${line(ctx.facilityName, 300)}</div><div class="f">Facility Code: ${line()}</div></div>
      <div class="frow"><div class="f">From: ${line('Main Store', 200)}</div><div class="f">To: ${line(to, 200)}</div></div>
    </div>
    <table><thead>
      <tr><th rowspan="2">Serial No</th><th rowspan="2" style="width:26%">Item Description and Strength</th><th rowspan="2">Pack Size</th>
        <th>Requisition</th><th colspan="4">To be filled by storekeeper</th></tr>
      <tr><th>Stock Balance</th><th>Qty Required</th><th>Qty Issued</th><th>Batch #</th><th>Expiry Date</th><th>Remarks</th></tr></thead>
      <tbody>${lineRows}${blanks}</tbody></table>
    <div class="sigs">${sigRow('Requisition Prepared by (Full Name):')}${sigRow('Requisition Recommended by (Full Name):')}${sigRow('Requisition Approved by (Full Name):')}${sigRow('Commodities Issued by (Full Name):')}${sigRow('Commodities Received by (Full Name):')}</div>`
  openPrint(`Internal RIRV — ${to}`, inner)
}

// ── TRANSFER & RETURN ─────────────────────────────────────────────────────
// External redistribution/return to ONE receiving facility. moveRows: the
// transfer rows of one move (same source, same receiving facility, same day).
// Batch/expiry are the RECORDED values from the transfer notes.
export function printTransfer(moveRows, ctx = {}) {
  const rows = moveRows || []
  const first = rows[0] || {}
  const from = first.sending_facility_name || ctx.facilityName || ''
  const to = first.receiving_facility_name || ''
  const reason = n => String(n || '').replace(/\[[^\]]*\]/g, '').trim()   // strip [tags] → free note
  const lineRows = rows.map((r, i) => '<tr>' + `<td>${i + 1}</td>` + `<td class="l">${esc(r.commodity_name)}</td>`
    + `<td>${esc(rx(r.notes, 'Batch') || '')}</td>` + `<td>${esc(rx(r.notes, 'Expiry') || '')}</td>`
    + `<td class="n">${q(r.quantity)}</td>` + `<td class="l">${esc(reason(r.notes))}</td></tr>`).join('')
  const pad = Math.max(0, Math.min(10, 6 - rows.length))
  const blanks = Array.from({ length: pad }, (_, i) => `<tr><td>${rows.length + i + 1}</td>${'<td></td>'.repeat(5)}</tr>`).join('')
  const carrier = rx(first.notes, 'Carrier') || ''
  const approvedBy = rx(first.notes, 'Approved by') || ''

  const inner = armsHeader('RECORD FOR TRANSFERRING / RETURNING COMMODITIES') + `
    <div class="fields">
      <div class="frow"><div class="f">Name of facility returning/transferring commodities: ${line(from, 300)}</div></div>
      <div class="frow"><div class="f">Sent to: ${line(to, 320)}</div></div>
    </div>
    <table><thead><tr><th>S/No</th><th style="width:34%">Product Description</th><th>Batch No.</th><th>Expiry Date</th><th>Quantity</th><th style="width:26%">Reason for return / transfer</th></tr></thead>
      <tbody>${lineRows}${blanks}</tbody></table>
    <div class="sigs two">${sigRow('Record compiled by:', first.initiated_by || '')}${sigRow('Record approved by:', approvedBy)}${sigRow('Transfer / return by:')}</div>
    <div class="cert"><b>Carrier:</b> I certify that the above quantities of transfer/return were received by me except where explained below.
      <div class="cm">Comments: ${line('', 520)}</div>
      <div class="sg">Name of Carrier: ${line(carrier, 160)} Designation: ${line('', 120)} Signature: ${line('', 120)} Date: ${line('', 80)}</div></div>
    <div class="cert"><b>Receiving Facility:</b> I certify that the above quantities were received by me except where explained below (please explain the condition of items on receipt).
      <div class="cm">Comments: ${line('', 520)}</div>
      <div class="sg">Receiver's name: ${line('', 160)} Signature: ${line('', 120)} Date: ${line('', 80)}</div>
      <div class="sg">Transfer approved by: ${line('', 160)} Signature: ${line('', 120)} Date: ${line('', 80)}</div></div>
    <div class="note">NOTE: TO BE COMPLETED IN TRIPLICATES</div>`
  openPrint(`Transfer & Return — ${to}`, inner)
}

// ── CRRF (Combined Report and Requisition Form) ───────────────────────────
// Driven by a template list (full, ordered, grouped) so every row prints even
// when the facility has none — zeros seeded. `rows` are the template rows the
// page already matched to data: { group } | { sno, name, unit, pack, A, received,
// dispensed, adjPos, adjNeg, losses, E, F, G }.
const z = n => Number(n || 0).toLocaleString()

function crrfFields(ctx = {}) {
  return `
  <div class="fields three">
    <div class="frow"><div class="f">Facility Name: ${line(ctx.facilityName, 200)}</div><div class="f">Reporting Period Start: ${line(ctx.periodStart, 100)}</div><div class="f">Maximum Stock Level: ${line(ctx.maxLevel || '4 Months', 70)}</div></div>
    <div class="frow"><div class="f">Facility Code: ${line()}</div><div class="f">Reporting Period End: ${line(ctx.periodEnd, 100)}</div><div class="f">Minimum Stock Level: ${line(ctx.minLevel || '2 Months', 70)}</div></div>
    <div class="frow"><div class="f">LGA: ${line(ctx.lga, 150)}</div><div class="f">Date Prepared: ${line()}</div></div>
    <div class="frow"><div class="f">State: ${line(ctx.state, 150)}</div></div>
  </div>`
}

const expiryOfficers = officers => `
  <div class="sub-h">Expiry Details / Additional Remarks</div>
  <div class="hint">1. Please provide details (expiry dates) &nbsp; 2. Any other information</div>
  <table class="mini"><thead><tr><th>Description</th><th>Lot No</th><th>Exp date</th><th>Quantity</th></tr></thead>
    <tbody><tr><td></td><td></td><td></td><td></td></tr><tr><td></td><td></td><td></td><td></td></tr></tbody></table>
  <div class="sub-h">Reporting Officers Details</div>
  ${officers.map(o => `<div class="sg"><span class="lbl">${o}</span> ${line('', 180)} <span class="lbl">Phone</span> ${line('', 120)} <span class="lbl">Date</span> ${line('', 80)}</div>`).join('')}`

// ── CRRF — Pharmacy ARV/OI ───────────────────────────────────────────────
export function printCrrfArv(rows, ctx = {}) {
  let n = 0
  const body = rows.map(r => r.group
    ? `<tr class="grp"><td></td><td class="l" colspan="11">${esc(r.group)}</td></tr>`
    : (n++, '<tr>' + `<td>${n}</td><td class="l">${esc(r.name)}</td><td>${esc(r.unit || '')}</td>`
      + `<td class="n">${z(r.A)}</td><td class="n">${z(r.received)}</td><td class="n">${z(r.dispensed)}</td>`
      + `<td class="n">${z(r.adjPos)}</td><td class="n">${z(r.adjNeg)}</td><td class="n b">${z(r.E)}</td>`
      + `<td class="n">${z(r.F)}</td><td class="n b">${z(r.G)}</td><td class="l"></td></tr>`)).join('')
  const inner = armsHeader('COMBINED REPORT AND REQUISITION FORM (CRRF) - Antiretroviral and OIs') + crrfFields(ctx) + `
    <table class="crrf"><thead>
      <tr><th rowspan="3">S/No</th><th rowspan="3" style="width:22%">Drugs</th><th rowspan="3">Basic Unit</th><th colspan="6" class="rep">REPORT</th><th colspan="2" class="req">REQUISITION</th><th rowspan="3">Remarks</th></tr>
      <tr><th rowspan="2">Beginning Balance</th><th rowspan="2">Qty Received</th><th rowspan="2">Qty Dispensed</th><th colspan="2">Losses &amp; Adjustments</th><th rowspan="2">Ending Balance (Physical Count)</th><th rowspan="2">Max Stock Qty</th><th rowspan="2">Qty to Order</th></tr>
      <tr><th>Positive +</th><th>Negative &#8722;</th></tr>
      <tr class="keys"><th></th><th></th><th></th><th>A</th><th>B</th><th>C</th><th>D (+)</th><th>D (&#8722;)</th><th>E</th><th>F = C&#215;2</th><th>G = F&#8722;E</th><th>H</th></tr></thead>
      <tbody>${body}</tbody></table>`
  openPrint('CRRF — ARVs & OIs', inner)
}

// ── CRRF — Pharmacy Condoms & Lubricants ─────────────────────────────────
export function printCrrfCondom(rows, ctx = {}) {
  let n = 0
  const body = rows.map(r => r.group
    ? `<tr class="grp"><td></td><td class="l" colspan="14">${esc(r.group)}</td></tr>`
    : (n++, '<tr>' + `<td>${n}</td><td class="l">${esc(r.name)}</td><td>${esc(r.pack || '')}</td><td>${esc(r.unit || '')}</td>`
      + `<td class="n">${z(r.A)}</td><td class="n">${z(r.received)}</td><td class="n">${z(r.dispensed)}</td><td class="n">${z(r.distributed)}</td>`
      + `<td class="n">${z(r.adjPos)}</td><td class="n">${z(r.adjNeg)}</td><td class="n">${z(r.losses)}</td><td class="n b">${z(r.E)}</td>`
      + `<td class="n">${z(r.F)}</td><td class="n b">${z(r.G)}</td><td class="l"></td></tr>`)).join('')
  const bimonthly = `
    <div class="sub-h">Bimonthly Summary of Usage</div>
    <table class="mini"><thead><tr><th style="width:30%">Item</th><th>Distributed to Target Group</th><th>Quality Control</th><th>Condom Demonstration</th><th>Advocacy</th><th>TOTAL</th></tr></thead>
      <tbody>${rows.filter(r => !r.group).map(r => `<tr><td class="l">${esc(r.name)}</td><td></td><td></td><td></td><td></td><td></td></tr>`).join('')}</tbody></table>`
  const inner = armsHeader('COMBINED REPORT AND REQUISITION FORM (CRRF) - CONDOM &amp; LUBRICANT', 'Condoms &amp; Lubricants') + crrfFields(ctx) + `
    <table class="crrf sm"><thead>
      <tr><th rowspan="3">Serial No.</th><th rowspan="3" style="width:20%">Item Description</th><th rowspan="3">Pack Size</th><th rowspan="3">Reporting Unit</th>
          <th colspan="8">&nbsp;</th><th colspan="2" class="req">REQUISITION / ISSUE</th><th rowspan="3">Remarks</th></tr>
      <tr><th rowspan="2">Beginning Balance</th><th rowspan="2">Qty Received</th><th rowspan="2">Qty Used</th><th rowspan="2">No. distributed</th><th colspan="2">Adjustments (+/&#8722;)</th><th rowspan="2">Losses</th><th rowspan="2">Physical Count</th><th rowspan="2">Max Stock (Qty)</th><th rowspan="2">Qty to Order</th></tr>
      <tr><th>+</th><th>&#8722;</th></tr>
      <tr class="keys"><th></th><th></th><th></th><th></th><th>A</th><th>B</th><th>C</th><th>D</th><th>E+</th><th>E&#8722;</th><th>F</th><th>G</th><th>H = C&#215;2</th><th>I = H&#8722;G</th><th>J</th></tr></thead>
      <tbody>${body}</tbody></table>
    ${bimonthly}
    ${expiryOfficers(['Report Prepared by (Full Name &amp; Signature):', 'Requisition Approved by (Full Name &amp; Signature):'])}`
  openPrint('CRRF — Condoms & Lubricants', inner)
}

// ── CRRF — Lab CD4 ────────────────────────────────────────────────────────
// Equipment downtime block (blank — no data captured for it in the system).
const equipmentDowntime = `
  <div class="sub-h">Equipment Downtime</div>
  <div class="hint">Record any period the analyzer was non-functional during the reporting period.</div>
  <table class="mini"><thead><tr><th style="width:34%">Equipment</th><th>Serial No.</th><th>Date Down</th><th>Date Restored</th><th>Reason</th></tr></thead>
    <tbody><tr><td></td><td></td><td></td><td></td><td></td></tr><tr><td></td><td></td><td></td><td></td><td></td></tr></tbody></table>`

export function printCrrfCd4(rows, ctx = {}) {
  let n = 0
  const body = rows.map(r => r.group
    ? `<tr class="grp"><td></td><td class="l" colspan="12">${esc(r.group)}</td></tr>`
    : (n++, '<tr>' + `<td>${n}</td><td class="l">${esc(r.name)}</td><td>${esc(r.pack || '')}</td><td>${esc(r.unit || '')}</td>`
      + `<td class="n">${z(r.A)}</td><td class="n">${z(r.received)}</td><td class="n">${z(r.dispensed)}</td>`
      + `<td class="n">${z(r.adjPos)}</td><td class="n">${z(r.adjNeg)}</td><td class="n">${z(r.losses)}</td><td class="n b">${z(r.E)}</td>`
      + `<td class="n">${z(r.F)}</td><td class="n b">${z(r.G)}</td><td class="l"></td></tr>`)).join('')
  const inner = armsHeader('COMBINED REPORT AND REQUISITION FORM (CRRF) - CD4', 'CD4 Reagents &amp; Consumables') + crrfFields(ctx) + `
    <table class="crrf sm"><thead>
      <tr><th rowspan="3">S/No</th><th rowspan="3" style="width:22%">Reagent / Item Description</th><th rowspan="3">Pack Size</th><th rowspan="3">Reporting Unit</th>
          <th colspan="7" class="rep">REPORT</th><th colspan="2" class="req">REQUISITION</th><th rowspan="3">Remarks</th></tr>
      <tr><th rowspan="2">Beginning Balance</th><th rowspan="2">Qty Received</th><th rowspan="2">No. of Tests Done</th><th colspan="2">Adjustments</th><th rowspan="2">Losses</th><th rowspan="2">Ending Balance (Physical Count)</th><th rowspan="2">Max Stock Qty</th><th rowspan="2">Qty to Order</th></tr>
      <tr><th>Positive +</th><th>Negative &#8722;</th></tr>
      <tr class="keys"><th></th><th></th><th></th><th></th><th>A</th><th>B</th><th>C</th><th>D (+)</th><th>D (&#8722;)</th><th>E</th><th>F</th><th>G = C&#215;2</th><th>H = G&#8722;F</th><th>I</th></tr></thead>
      <tbody>${body}</tbody></table>
    ${equipmentDowntime}
    ${expiryOfficers(['Report Prepared by (Full Name &amp; Signature):', 'Requisition Approved by (Full Name &amp; Signature):'])}
    <div class="ver">Version 2022</div>`
  openPrint('CRRF — CD4', inner)
}

// ── CRRF — Lab HIV RTKs & DBS ─────────────────────────────────────────────
export function printCrrfRtk(rows, ctx = {}) {
  let n = 0
  const body = rows.map(r => r.group
    ? `<tr class="grp"><td></td><td class="l" colspan="11">${esc(r.group)}</td></tr>`
    : (n++, '<tr>' + `<td>${n}</td><td class="l">${esc(r.name)}</td><td>${esc(r.unit || '')}</td>`
      + `<td class="n">${z(r.A)}</td><td class="n">${z(r.received)}</td><td class="n">${z(r.dispensed)}</td>`
      + `<td class="n">${z(r.adjPos)}</td><td class="n">${z(r.adjNeg)}</td><td class="n">${z(r.losses)}</td><td class="n b">${z(r.E)}</td>`
      + `<td class="n">${z(r.F)}</td><td class="n b">${z(r.G)}</td><td class="l"></td></tr>`)).join('')
  // Bimonthly test summary — blank (per-programme test counts aren't captured).
  const testSummary = `
    <div class="sub-h">Bimonthly Summary of Tests Conducted</div>
    <table class="mini"><thead><tr><th style="width:30%">Test Kit</th><th>HTS</th><th>PMTCT</th><th>TB/HIV</th><th>Others</th><th>TOTAL</th></tr></thead>
      <tbody>${rows.filter(r => !r.group).map(r => `<tr><td class="l">${esc(r.name)}</td><td></td><td></td><td></td><td></td><td></td></tr>`).join('')}</tbody></table>`
  const inner = armsHeader('COMBINED REPORT AND REQUISITION FORM (CRRF) - HIV RTKs &amp; DBS', 'HIV Rapid Test Kits &amp; DBS') + crrfFields(ctx) + `
    <table class="crrf sm"><thead>
      <tr><th rowspan="3">S/No</th><th rowspan="3" style="width:26%">Test Kit / Item</th><th rowspan="3">Reporting Unit</th>
          <th colspan="7" class="rep">REPORT</th><th colspan="2" class="req">REQUISITION</th><th rowspan="3">Remarks</th></tr>
      <tr><th rowspan="2">Beginning Balance</th><th rowspan="2">Qty Received</th><th rowspan="2">No. of Tests Done</th><th colspan="2">Adjustments</th><th rowspan="2">Losses</th><th rowspan="2">Ending Balance (Physical Count)</th><th rowspan="2">Max Stock Qty</th><th rowspan="2">Qty to Order</th></tr>
      <tr><th>Positive +</th><th>Negative &#8722;</th></tr>
      <tr class="keys"><th></th><th></th><th></th><th>A</th><th>B</th><th>C</th><th>D (+)</th><th>D (&#8722;)</th><th>E</th><th>F</th><th>G = C&#215;2</th><th>H = G&#8722;F</th><th>I</th></tr></thead>
      <tbody>${body}</tbody></table>
    ${testSummary}
    ${expiryOfficers(['Report Prepared by (Full Name &amp; Signature):', 'Requisition Approved by (Full Name &amp; Signature):'])}
    <div class="ver">Version 2022</div>`
  openPrint('CRRF — HIV RTKs & DBS', inner)
}
