// National LMIS print forms — exact-match reproductions of the government tools
// (Bin Card, Internal RIRV, Transfer & Return, CRRF variants) with the Nigerian
// coat of arms. Opened via the app's Print / Save as PDF buttons. This module is
// dynamically imported so the ~420KB coat-of-arms SVG stays out of the main bundle.
import ncoa from '../assets/ncoa.svg?raw'
import { toast } from '../components/ui/Toast'
import { fmtDate } from './helpers'

const esc = s => String(s == null ? '' : s).replace(/[&<>]/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;' }[c]))
const dstr = d => (d ? fmtDate(d) : '')
// Movement cells: show the number, blank when zero/empty (paper-form convention).
const q = n => (n === 0 || n == null || n === '') ? '' : Number(n).toLocaleString()
const signed = n => n > 0 ? `+${Number(n).toLocaleString()}` : n < 0 ? Number(n).toLocaleString() : ''
const line = (v = '', w = 90) => `<span class="fill" style="min-width:${w}px">${esc(v)}</span>`

// Shared print stylesheet — ported verbatim from the approved preview.
const CSS = `
  *{ box-sizing:border-box; font-family:Arial,Helvetica,sans-serif; -webkit-print-color-adjust:exact; print-color-adjust:exact; }
  body{ margin:0; color:#111; }
  .paper{ padding:10mm 10mm 12mm; }
  .hdr{ display:flex; align-items:center; gap:18px; border-bottom:2px solid #000; padding-bottom:8px; }
  .arms{ width:78px; height:66px; flex:none; display:flex; align-items:center; justify-content:center; }
  .arms svg{ height:64px; width:auto; }
  .ttl{ flex:1; text-align:center; }
  .ftitle{ font-size:16px; font-weight:800; letter-spacing:1px; }
  .fsub-band{ border:1px solid #000; border-top:none; text-align:center; font-weight:700; font-size:12px; padding:3px 4px; }
  .fsub-band u{ font-weight:700; }
  .fields{ margin:12px 0 8px; font-size:11.5px; line-height:2.0; }
  .frow{ display:flex; gap:24px; } .f{ flex:1; }
  .hint{ color:#666; font-size:9.5px; }
  .fill{ display:inline-block; border-bottom:1px solid #000; padding:0 4px; min-height:15px; }
  table{ width:100%; border-collapse:collapse; font-size:10.5px; margin-top:4px; }
  th,td{ border:1px solid #000; padding:4px 6px; text-align:center; }
  th{ background:#e9e9e9; font-size:9.5px; line-height:1.15; font-weight:700; }
  td.l{ text-align:left; } td.n{ text-align:right; font-variant-numeric:tabular-nums; } td.b{ font-weight:700; }
  tbody tr{ height:25px; }
  tr.close td{ background:#e9eef5; font-weight:700; }
  .red{ color:#c0121a; font-weight:700; }
  .foot{ font-size:9px; color:#555; margin-top:8px; text-align:right; }
  @page{ size:landscape; margin:8mm; }
`

function armsHeader(title, sub = '') {
  const band = sub ? `<div class="fsub-band">${sub}</div>` : ''
  return `<div class="hdr"><div class="ttl"><div class="ftitle">${esc(title)}</div></div>`
    + `<div class="arms">${ncoa}</div></div>${band}`
}

// Open a print window with the given inner HTML, trigger the print dialog.
function openPrint(title, inner) {
  const doc = `<!DOCTYPE html><html><head><meta charset="utf-8"><title>${esc(title)}</title>`
    + `<style>${CSS}</style></head><body><div class="paper">${inner}</div>`
    + `<div class="foot">Generated by EnVo LMIS · ${esc(new Date().toLocaleString('en-GB'))}</div></body></html>`
  const url = URL.createObjectURL(new Blob([doc], { type: 'text/html' }))
  const win = window.open(url, '_blank')
  if (win) {
    win.onload = () => { win.focus(); win.print(); URL.revokeObjectURL(url); win.onafterprint = () => win.close() }
  } else {
    URL.revokeObjectURL(url)
    toast('Allow pop-ups to print / export PDF', 'red')
  }
}

// ── BIN CARD ──────────────────────────────────────────────────────────────
// Which of MAIN STORE / SUB STORE / DISPENSARY this bin is, for the subtitle.
function binKindLabel(location) {
  if (location === 'store') return 'MAIN STORE'
  if (location === 'dispensary') return 'DISPENSARY'
  return 'SUB STORE'   // DSD / SDP sites
}
const isGhsc = p => /ghsc/i.test(p || '')

export function printBinCard(card, locationLabel) {
  const comm = card?.commodity || {}
  const active = binKindLabel(card?.location)
  const sub = ['MAIN STORE', 'SUB STORE', 'DISPENSARY']
    .map(k => k === active ? `<u>${k}</u>` : k).join(' / ')

  // Opening balance, then movement rows with a monthly close-out band each month.
  const rows = card?.rows || []
  const bodyRows = []
  bodyRows.push(`<tr><td></td><td></td><td class="l">Balance b/f</td><td></td><td></td>`
    + `<td></td><td></td><td></td><td class="n b">${q(card?.openingBalance) || 0}</td><td></td><td></td></tr>`)

  const monthKey = d => { const x = new Date(d); return isNaN(x) ? '' : `${x.getFullYear()}-${x.getMonth()}` }
  const monthName = d => new Date(d).toLocaleString('en-GB', { month: 'long', year: 'numeric', timeZone: 'Africa/Lagos' }).toUpperCase()
  let curKey = null, mRecv = 0, mIss = 0, mAdj = 0, mBal = null, mDate = null
  const flush = () => {
    if (curKey == null) return
    bodyRows.push(`<tr class="close"><td colspan="2">${esc(monthName(mDate))} CLOSE-OUT</td>`
      + `<td>Monthly summary</td><td></td><td></td>`
      + `<td class="n">${q(mRecv)}</td><td class="n">${q(mIss)}</td><td class="n">${signed(mAdj)}</td>`
      + `<td class="n b">${q(mBal)}</td><td></td><td></td></tr>`)
  }
  for (const r of rows) {
    const k = monthKey(r.date)
    if (k !== curKey) { flush(); curKey = k; mRecv = 0; mIss = 0; mAdj = 0; mDate = r.date }
    mRecv += r.received || 0; mIss += r.issued || 0; mAdj += r.adjustment || 0; mBal = r.balance; mDate = r.date
    const party = String(r.party || '').replace(/^→\s*/, '')   // no arrows on the form
    const partyCell = isGhsc(party) ? `<td class="l red">${esc(party)}</td>` : `<td class="l">${esc(party)}</td>`
    bodyRows.push('<tr>' + `<td>${dstr(r.date)}</td><td>${esc(r.ref)}</td>` + partyCell
      + `<td>${esc(r.batch)}</td><td>${dstr(r.expiry)}</td>`
      + `<td class="n">${q(r.received)}</td><td class="n">${q(r.issued)}</td><td class="n">${signed(r.adjustment)}</td>`
      + `<td class="n b">${q(r.balance)}</td><td>${esc(r.by)}</td><td class="l">${esc(r.remarks)}</td></tr>`)
  }
  flush()

  const inner = armsHeader('BIN CARD', `( ${sub} )`) + `
    <div class="fields">
      <div class="frow"><div class="f">Name of Facility: ${line(card?.facility?.name, 340)}</div></div>
      <div class="frow"><div class="f">Item Description: ${line(comm.name, 240)} <span class="hint">(Name, Strength, Dosage Form)</span></div>
        <div class="f">Product Code: ${line()}</div><div class="f">Card No: ${line()}</div></div>
      <div class="frow"><div class="f">Unit of Measure: ${line(comm.unit)}</div><div class="f">Location / Shelf No: ${line()}</div></div>
    </div>
    <table><thead>
      <tr><th rowspan="2">Date</th><th rowspan="2">Voucher / Ref. No</th><th rowspan="2" style="width:16%">Received From / Issued to</th>
        <th rowspan="2">Batch No.</th><th rowspan="2">Expiry Date</th><th colspan="3">Quantity</th>
        <th rowspan="2">Balance</th><th rowspan="2">Signature</th><th rowspan="2">Remarks</th></tr>
      <tr><th>Received</th><th>Issued</th><th>Losses &amp; Adj.</th></tr></thead>
      <tbody>${bodyRows.join('')}</tbody></table>`
  openPrint(`Bin Card — ${comm.name || ''}`, inner)
}
